#!/usr/bin/env bash
perl-rename -n 's/ /_/g' *.mp3
perl-rename -n 's/_-_/-/g' *.mp3
perl-rename 's/ /_/g' *.mp3
perl-rename 's/_-_/-/g' *.mp3
for f in *; do ffmpeg -i $f -acodec pcm_s16le -ar 44100 -ac 2 ${f%.*}.wav; done
normalize -b -v *.wav
cdrecord -v -eject dev='/dev/sr0' -audio -pad *.wav
rm -v *.wav
