#!/usr/bin/env python

from getpass import getpass
from subprocess import call
from time import sleep
from os import remove

password_file_name = '/tmp/.gmail_password'

password = getpass()
with open(password_file_name, 'w') as password_file:
    password_file.write(password)
call(['i3-msg', 'restart'])
sleep(3)
remove(password_file_name)
